# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bakerstreet import bakerstreet_bridge_pb2 as bakerstreet_dot_bakerstreet__bridge__pb2
from bakerstreet import bakerstreet_pb2 as bakerstreet_dot_bakerstreet__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bakerstreet/bakerstreet_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MoriartyBridgeStub:
    """═══════════════════════════════════════════════════════════
    SERVICE: MoriartyBridge — device-facing (bidi stream)
    ═══════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/com.appknox.bakerstreet.MoriartyBridge/Connect',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.DeviceMessage.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.ServerMessage.FromString,
                _registered_method=True)


class MoriartyBridgeServicer:
    """═══════════════════════════════════════════════════════════
    SERVICE: MoriartyBridge — device-facing (bidi stream)
    ═══════════════════════════════════════════════════════════

    """

    def Connect(self, request_iterator, context):
        """Device opens this on startup and keeps it alive.
        Relay pushes Command messages, device pushes CommandResponse messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoriartyBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.DeviceMessage.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.appknox.bakerstreet.MoriartyBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.appknox.bakerstreet.MoriartyBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MoriartyBridge:
    """═══════════════════════════════════════════════════════════
    SERVICE: MoriartyBridge — device-facing (bidi stream)
    ═══════════════════════════════════════════════════════════

    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.appknox.bakerstreet.MoriartyBridge/Connect',
            bakerstreet_dot_bakerstreet__bridge__pb2.DeviceMessage.SerializeToString,
            bakerstreet_dot_bakerstreet__bridge__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MoriartyDispatchStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/Echo',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedMessage.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.LaunchApp = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/LaunchApp',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.ClearProxy = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/ClearProxy',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/HealthCheck',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.RemovePackage = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/RemovePackage',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.InstallPackage = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/InstallPackage',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedInstallReq.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.ConfigureProxy = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/ConfigureProxy',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedConfigProxyReq.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.ConfigureGadget = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/ConfigureGadget',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.StartAutoPilot = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/StartAutoPilot',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedAutoPilotConfig.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.Clean = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/Clean',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedCleanOptions.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Message.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/Info',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Device.FromString,
                _registered_method=True)
        self.InfoV2 = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/InfoV2',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.DeviceV2.FromString,
                _registered_method=True)
        self.ListPackages = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/ListPackages',
                request_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__pb2.Apps.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/com.appknox.bakerstreet.MoriartyDispatch/ListDevices',
                request_serializer=bakerstreet_dot_bakerstreet__pb2.Empty.SerializeToString,
                response_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.DeviceList.FromString,
                _registered_method=True)


class MoriartyDispatchServicer:
    """Missing associated documentation comment in .proto file."""

    def Echo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LaunchApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearProxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallPackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureProxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureGadget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAutoPilot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InfoV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPackages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Discover all currently connected relay devices
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoriartyDispatchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedMessage.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'LaunchApp': grpc.unary_unary_rpc_method_handler(
                    servicer.LaunchApp,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'ClearProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearProxy,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'RemovePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePackage,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'InstallPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallPackage,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedInstallReq.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'ConfigureProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureProxy,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedConfigProxyReq.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'ConfigureGadget': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureGadget,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'StartAutoPilot': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAutoPilot,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedAutoPilotConfig.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'Clean': grpc.unary_unary_rpc_method_handler(
                    servicer.Clean,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedCleanOptions.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Message.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Device.SerializeToString,
            ),
            'InfoV2': grpc.unary_unary_rpc_method_handler(
                    servicer.InfoV2,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.DeviceV2.SerializeToString,
            ),
            'ListPackages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPackages,
                    request_deserializer=bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__pb2.Apps.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=bakerstreet_dot_bakerstreet__pb2.Empty.FromString,
                    response_serializer=bakerstreet_dot_bakerstreet__bridge__pb2.DeviceList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.appknox.bakerstreet.MoriartyDispatch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.appknox.bakerstreet.MoriartyDispatch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MoriartyDispatch:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/Echo',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedMessage.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LaunchApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/LaunchApp',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/ClearProxy',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/HealthCheck',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/RemovePackage',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/InstallPackage',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedInstallReq.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/ConfigureProxy',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedConfigProxyReq.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureGadget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/ConfigureGadget',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedApp.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAutoPilot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/StartAutoPilot',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedAutoPilotConfig.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/Clean',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedCleanOptions.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/Info',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Device.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InfoV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/InfoV2',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.DeviceV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPackages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/ListPackages',
            bakerstreet_dot_bakerstreet__bridge__pb2.TargetedEmpty.SerializeToString,
            bakerstreet_dot_bakerstreet__pb2.Apps.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.appknox.bakerstreet.MoriartyDispatch/ListDevices',
            bakerstreet_dot_bakerstreet__pb2.Empty.SerializeToString,
            bakerstreet_dot_bakerstreet__bridge__pb2.DeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
