// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: bakerstreet/bakerstreet_bridge.proto

package bakerstreet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MoriartyBridge_Connect_FullMethodName = "/com.appknox.bakerstreet.MoriartyBridge/Connect"
)

// MoriartyBridgeClient is the client API for MoriartyBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoriartyBridgeClient interface {
	// Device opens this on startup and keeps it alive.
	// Relay pushes Command messages, device pushes CommandResponse messages.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceMessage, ServerMessage], error)
}

type moriartyBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewMoriartyBridgeClient(cc grpc.ClientConnInterface) MoriartyBridgeClient {
	return &moriartyBridgeClient{cc}
}

func (c *moriartyBridgeClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MoriartyBridge_ServiceDesc.Streams[0], MoriartyBridge_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeviceMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MoriartyBridge_ConnectClient = grpc.BidiStreamingClient[DeviceMessage, ServerMessage]

// MoriartyBridgeServer is the server API for MoriartyBridge service.
// All implementations must embed UnimplementedMoriartyBridgeServer
// for forward compatibility.
type MoriartyBridgeServer interface {
	// Device opens this on startup and keeps it alive.
	// Relay pushes Command messages, device pushes CommandResponse messages.
	Connect(grpc.BidiStreamingServer[DeviceMessage, ServerMessage]) error
	mustEmbedUnimplementedMoriartyBridgeServer()
}

// UnimplementedMoriartyBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoriartyBridgeServer struct{}

func (UnimplementedMoriartyBridgeServer) Connect(grpc.BidiStreamingServer[DeviceMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMoriartyBridgeServer) mustEmbedUnimplementedMoriartyBridgeServer() {}
func (UnimplementedMoriartyBridgeServer) testEmbeddedByValue()                        {}

// UnsafeMoriartyBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoriartyBridgeServer will
// result in compilation errors.
type UnsafeMoriartyBridgeServer interface {
	mustEmbedUnimplementedMoriartyBridgeServer()
}

func RegisterMoriartyBridgeServer(s grpc.ServiceRegistrar, srv MoriartyBridgeServer) {
	// If the following call panics, it indicates UnimplementedMoriartyBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoriartyBridge_ServiceDesc, srv)
}

func _MoriartyBridge_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MoriartyBridgeServer).Connect(&grpc.GenericServerStream[DeviceMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MoriartyBridge_ConnectServer = grpc.BidiStreamingServer[DeviceMessage, ServerMessage]

// MoriartyBridge_ServiceDesc is the grpc.ServiceDesc for MoriartyBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoriartyBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.appknox.bakerstreet.MoriartyBridge",
	HandlerType: (*MoriartyBridgeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _MoriartyBridge_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bakerstreet/bakerstreet_bridge.proto",
}

const (
	MoriartyDispatch_Echo_FullMethodName            = "/com.appknox.bakerstreet.MoriartyDispatch/Echo"
	MoriartyDispatch_LaunchApp_FullMethodName       = "/com.appknox.bakerstreet.MoriartyDispatch/LaunchApp"
	MoriartyDispatch_ClearProxy_FullMethodName      = "/com.appknox.bakerstreet.MoriartyDispatch/ClearProxy"
	MoriartyDispatch_HealthCheck_FullMethodName     = "/com.appknox.bakerstreet.MoriartyDispatch/HealthCheck"
	MoriartyDispatch_RemovePackage_FullMethodName   = "/com.appknox.bakerstreet.MoriartyDispatch/RemovePackage"
	MoriartyDispatch_InstallPackage_FullMethodName  = "/com.appknox.bakerstreet.MoriartyDispatch/InstallPackage"
	MoriartyDispatch_ConfigureProxy_FullMethodName  = "/com.appknox.bakerstreet.MoriartyDispatch/ConfigureProxy"
	MoriartyDispatch_ConfigureGadget_FullMethodName = "/com.appknox.bakerstreet.MoriartyDispatch/ConfigureGadget"
	MoriartyDispatch_StartAutoPilot_FullMethodName  = "/com.appknox.bakerstreet.MoriartyDispatch/StartAutoPilot"
	MoriartyDispatch_Clean_FullMethodName           = "/com.appknox.bakerstreet.MoriartyDispatch/Clean"
	MoriartyDispatch_Info_FullMethodName            = "/com.appknox.bakerstreet.MoriartyDispatch/Info"
	MoriartyDispatch_InfoV2_FullMethodName          = "/com.appknox.bakerstreet.MoriartyDispatch/InfoV2"
	MoriartyDispatch_ListPackages_FullMethodName    = "/com.appknox.bakerstreet.MoriartyDispatch/ListPackages"
	MoriartyDispatch_ListDevices_FullMethodName     = "/com.appknox.bakerstreet.MoriartyDispatch/ListDevices"
)

// MoriartyDispatchClient is the client API for MoriartyDispatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoriartyDispatchClient interface {
	Echo(ctx context.Context, in *TargetedMessage, opts ...grpc.CallOption) (*Message, error)
	LaunchApp(ctx context.Context, in *TargetedApp, opts ...grpc.CallOption) (*Message, error)
	ClearProxy(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*Message, error)
	HealthCheck(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*Message, error)
	RemovePackage(ctx context.Context, in *TargetedApp, opts ...grpc.CallOption) (*Message, error)
	InstallPackage(ctx context.Context, in *TargetedInstallReq, opts ...grpc.CallOption) (*Message, error)
	ConfigureProxy(ctx context.Context, in *TargetedConfigProxyReq, opts ...grpc.CallOption) (*Message, error)
	ConfigureGadget(ctx context.Context, in *TargetedApp, opts ...grpc.CallOption) (*Message, error)
	StartAutoPilot(ctx context.Context, in *TargetedAutoPilotConfig, opts ...grpc.CallOption) (*Message, error)
	Clean(ctx context.Context, in *TargetedCleanOptions, opts ...grpc.CallOption) (*Message, error)
	Info(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*Device, error)
	InfoV2(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*DeviceV2, error)
	ListPackages(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*Apps, error)
	// Discover all currently connected relay devices
	ListDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceList, error)
}

type moriartyDispatchClient struct {
	cc grpc.ClientConnInterface
}

func NewMoriartyDispatchClient(cc grpc.ClientConnInterface) MoriartyDispatchClient {
	return &moriartyDispatchClient{cc}
}

func (c *moriartyDispatchClient) Echo(ctx context.Context, in *TargetedMessage, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) LaunchApp(ctx context.Context, in *TargetedApp, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_LaunchApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) ClearProxy(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_ClearProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) HealthCheck(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) RemovePackage(ctx context.Context, in *TargetedApp, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_RemovePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) InstallPackage(ctx context.Context, in *TargetedInstallReq, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_InstallPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) ConfigureProxy(ctx context.Context, in *TargetedConfigProxyReq, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_ConfigureProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) ConfigureGadget(ctx context.Context, in *TargetedApp, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_ConfigureGadget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) StartAutoPilot(ctx context.Context, in *TargetedAutoPilotConfig, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_StartAutoPilot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) Clean(ctx context.Context, in *TargetedCleanOptions, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MoriartyDispatch_Clean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) Info(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*Device, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Device)
	err := c.cc.Invoke(ctx, MoriartyDispatch_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) InfoV2(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*DeviceV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceV2)
	err := c.cc.Invoke(ctx, MoriartyDispatch_InfoV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) ListPackages(ctx context.Context, in *TargetedEmpty, opts ...grpc.CallOption) (*Apps, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Apps)
	err := c.cc.Invoke(ctx, MoriartyDispatch_ListPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyDispatchClient) ListDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DeviceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceList)
	err := c.cc.Invoke(ctx, MoriartyDispatch_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoriartyDispatchServer is the server API for MoriartyDispatch service.
// All implementations must embed UnimplementedMoriartyDispatchServer
// for forward compatibility.
type MoriartyDispatchServer interface {
	Echo(context.Context, *TargetedMessage) (*Message, error)
	LaunchApp(context.Context, *TargetedApp) (*Message, error)
	ClearProxy(context.Context, *TargetedEmpty) (*Message, error)
	HealthCheck(context.Context, *TargetedEmpty) (*Message, error)
	RemovePackage(context.Context, *TargetedApp) (*Message, error)
	InstallPackage(context.Context, *TargetedInstallReq) (*Message, error)
	ConfigureProxy(context.Context, *TargetedConfigProxyReq) (*Message, error)
	ConfigureGadget(context.Context, *TargetedApp) (*Message, error)
	StartAutoPilot(context.Context, *TargetedAutoPilotConfig) (*Message, error)
	Clean(context.Context, *TargetedCleanOptions) (*Message, error)
	Info(context.Context, *TargetedEmpty) (*Device, error)
	InfoV2(context.Context, *TargetedEmpty) (*DeviceV2, error)
	ListPackages(context.Context, *TargetedEmpty) (*Apps, error)
	// Discover all currently connected relay devices
	ListDevices(context.Context, *Empty) (*DeviceList, error)
	mustEmbedUnimplementedMoriartyDispatchServer()
}

// UnimplementedMoriartyDispatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoriartyDispatchServer struct{}

func (UnimplementedMoriartyDispatchServer) Echo(context.Context, *TargetedMessage) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedMoriartyDispatchServer) LaunchApp(context.Context, *TargetedApp) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method LaunchApp not implemented")
}
func (UnimplementedMoriartyDispatchServer) ClearProxy(context.Context, *TargetedEmpty) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearProxy not implemented")
}
func (UnimplementedMoriartyDispatchServer) HealthCheck(context.Context, *TargetedEmpty) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMoriartyDispatchServer) RemovePackage(context.Context, *TargetedApp) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePackage not implemented")
}
func (UnimplementedMoriartyDispatchServer) InstallPackage(context.Context, *TargetedInstallReq) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallPackage not implemented")
}
func (UnimplementedMoriartyDispatchServer) ConfigureProxy(context.Context, *TargetedConfigProxyReq) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureProxy not implemented")
}
func (UnimplementedMoriartyDispatchServer) ConfigureGadget(context.Context, *TargetedApp) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureGadget not implemented")
}
func (UnimplementedMoriartyDispatchServer) StartAutoPilot(context.Context, *TargetedAutoPilotConfig) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAutoPilot not implemented")
}
func (UnimplementedMoriartyDispatchServer) Clean(context.Context, *TargetedCleanOptions) (*Message, error) {
	return nil, status.Error(codes.Unimplemented, "method Clean not implemented")
}
func (UnimplementedMoriartyDispatchServer) Info(context.Context, *TargetedEmpty) (*Device, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedMoriartyDispatchServer) InfoV2(context.Context, *TargetedEmpty) (*DeviceV2, error) {
	return nil, status.Error(codes.Unimplemented, "method InfoV2 not implemented")
}
func (UnimplementedMoriartyDispatchServer) ListPackages(context.Context, *TargetedEmpty) (*Apps, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedMoriartyDispatchServer) ListDevices(context.Context, *Empty) (*DeviceList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedMoriartyDispatchServer) mustEmbedUnimplementedMoriartyDispatchServer() {}
func (UnimplementedMoriartyDispatchServer) testEmbeddedByValue()                          {}

// UnsafeMoriartyDispatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoriartyDispatchServer will
// result in compilation errors.
type UnsafeMoriartyDispatchServer interface {
	mustEmbedUnimplementedMoriartyDispatchServer()
}

func RegisterMoriartyDispatchServer(s grpc.ServiceRegistrar, srv MoriartyDispatchServer) {
	// If the following call panics, it indicates UnimplementedMoriartyDispatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoriartyDispatch_ServiceDesc, srv)
}

func _MoriartyDispatch_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).Echo(ctx, req.(*TargetedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_LaunchApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedApp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).LaunchApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_LaunchApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).LaunchApp(ctx, req.(*TargetedApp))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_ClearProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).ClearProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_ClearProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).ClearProxy(ctx, req.(*TargetedEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).HealthCheck(ctx, req.(*TargetedEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_RemovePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedApp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).RemovePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_RemovePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).RemovePackage(ctx, req.(*TargetedApp))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_InstallPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedInstallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).InstallPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_InstallPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).InstallPackage(ctx, req.(*TargetedInstallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_ConfigureProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedConfigProxyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).ConfigureProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_ConfigureProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).ConfigureProxy(ctx, req.(*TargetedConfigProxyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_ConfigureGadget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedApp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).ConfigureGadget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_ConfigureGadget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).ConfigureGadget(ctx, req.(*TargetedApp))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_StartAutoPilot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedAutoPilotConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).StartAutoPilot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_StartAutoPilot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).StartAutoPilot(ctx, req.(*TargetedAutoPilotConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_Clean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedCleanOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).Clean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_Clean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).Clean(ctx, req.(*TargetedCleanOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).Info(ctx, req.(*TargetedEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_InfoV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).InfoV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_InfoV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).InfoV2(ctx, req.(*TargetedEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetedEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_ListPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).ListPackages(ctx, req.(*TargetedEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoriartyDispatch_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyDispatchServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoriartyDispatch_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyDispatchServer).ListDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MoriartyDispatch_ServiceDesc is the grpc.ServiceDesc for MoriartyDispatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoriartyDispatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.appknox.bakerstreet.MoriartyDispatch",
	HandlerType: (*MoriartyDispatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _MoriartyDispatch_Echo_Handler,
		},
		{
			MethodName: "LaunchApp",
			Handler:    _MoriartyDispatch_LaunchApp_Handler,
		},
		{
			MethodName: "ClearProxy",
			Handler:    _MoriartyDispatch_ClearProxy_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MoriartyDispatch_HealthCheck_Handler,
		},
		{
			MethodName: "RemovePackage",
			Handler:    _MoriartyDispatch_RemovePackage_Handler,
		},
		{
			MethodName: "InstallPackage",
			Handler:    _MoriartyDispatch_InstallPackage_Handler,
		},
		{
			MethodName: "ConfigureProxy",
			Handler:    _MoriartyDispatch_ConfigureProxy_Handler,
		},
		{
			MethodName: "ConfigureGadget",
			Handler:    _MoriartyDispatch_ConfigureGadget_Handler,
		},
		{
			MethodName: "StartAutoPilot",
			Handler:    _MoriartyDispatch_StartAutoPilot_Handler,
		},
		{
			MethodName: "Clean",
			Handler:    _MoriartyDispatch_Clean_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _MoriartyDispatch_Info_Handler,
		},
		{
			MethodName: "InfoV2",
			Handler:    _MoriartyDispatch_InfoV2_Handler,
		},
		{
			MethodName: "ListPackages",
			Handler:    _MoriartyDispatch_ListPackages_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _MoriartyDispatch_ListDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bakerstreet/bakerstreet_bridge.proto",
}
