// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bakerstreet.proto

/*
Package com_appknox_bakerstreet is a generated protocol buffer package.

It is generated from these files:
	bakerstreet.proto

It has these top-level messages:
	Message
	Packages
	Device
	Finding
*/
package com_appknox_bakerstreet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Data        string `protobuf:"bytes,1,opt,name=Data,json=data" json:"Data,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=Title,json=title" json:"Title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,json=description" json:"Description,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Message) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Message) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Packages struct {
	Names []string `protobuf:"bytes,1,rep,name=Names,json=names" json:"Names,omitempty"`
}

func (m *Packages) Reset()                    { *m = Packages{} }
func (m *Packages) String() string            { return proto.CompactTextString(m) }
func (*Packages) ProtoMessage()               {}
func (*Packages) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Packages) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type Device struct {
	Uuid            string `protobuf:"bytes,1,opt,name=Uuid,json=uuid" json:"Uuid,omitempty"`
	IsTablet        bool   `protobuf:"varint,2,opt,name=IsTablet,json=isTablet" json:"IsTablet,omitempty"`
	Platform        int32  `protobuf:"varint,3,opt,name=Platform,json=platform" json:"Platform,omitempty"`
	PlatformVersion string `protobuf:"bytes,4,opt,name=PlatformVersion,json=platformVersion" json:"PlatformVersion,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Device) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Device) GetIsTablet() bool {
	if m != nil {
		return m.IsTablet
	}
	return false
}

func (m *Device) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *Device) GetPlatformVersion() string {
	if m != nil {
		return m.PlatformVersion
	}
	return ""
}

type Finding struct {
	Title       string `protobuf:"bytes,1,opt,name=Title,json=title" json:"Title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description,json=description" json:"Description,omitempty"`
}

func (m *Finding) Reset()                    { *m = Finding{} }
func (m *Finding) String() string            { return proto.CompactTextString(m) }
func (*Finding) ProtoMessage()               {}
func (*Finding) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Finding) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Finding) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "com.appknox.bakerstreet.Message")
	proto.RegisterType((*Packages)(nil), "com.appknox.bakerstreet.Packages")
	proto.RegisterType((*Device)(nil), "com.appknox.bakerstreet.Device")
	proto.RegisterType((*Finding)(nil), "com.appknox.bakerstreet.Finding")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Moriarty service

type MoriartyClient interface {
	Info(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Device, error)
	Echo(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	LaunchApp(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	HealthCheck(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	RemovePackage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	InstallPackage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	ListPackages(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Packages, error)
	ConfigureProxy(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	ConfigureGadget(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type moriartyClient struct {
	cc *grpc.ClientConn
}

func NewMoriartyClient(cc *grpc.ClientConn) MoriartyClient {
	return &moriartyClient{cc}
}

func (c *moriartyClient) Info(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyClient) Echo(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyClient) LaunchApp(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/LaunchApp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyClient) HealthCheck(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyClient) RemovePackage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/RemovePackage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyClient) InstallPackage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/InstallPackage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyClient) ListPackages(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Packages, error) {
	out := new(Packages)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/ListPackages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyClient) ConfigureProxy(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/ConfigureProxy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moriartyClient) ConfigureGadget(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Moriarty/ConfigureGadget", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Moriarty service

type MoriartyServer interface {
	Info(context.Context, *Message) (*Device, error)
	Echo(context.Context, *Message) (*Message, error)
	LaunchApp(context.Context, *Message) (*Message, error)
	HealthCheck(context.Context, *Message) (*Message, error)
	RemovePackage(context.Context, *Message) (*Message, error)
	InstallPackage(context.Context, *Message) (*Message, error)
	ListPackages(context.Context, *Message) (*Packages, error)
	ConfigureProxy(context.Context, *Message) (*Message, error)
	ConfigureGadget(context.Context, *Message) (*Message, error)
}

func RegisterMoriartyServer(s *grpc.Server, srv MoriartyServer) {
	s.RegisterService(&_Moriarty_serviceDesc, srv)
}

func _Moriarty_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).Info(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moriarty_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).Echo(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moriarty_LaunchApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).LaunchApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/LaunchApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).LaunchApp(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moriarty_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).HealthCheck(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moriarty_RemovePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).RemovePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/RemovePackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).RemovePackage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moriarty_InstallPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).InstallPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/InstallPackage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).InstallPackage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moriarty_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/ListPackages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).ListPackages(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moriarty_ConfigureProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).ConfigureProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/ConfigureProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).ConfigureProxy(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moriarty_ConfigureGadget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoriartyServer).ConfigureGadget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Moriarty/ConfigureGadget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoriartyServer).ConfigureGadget(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Moriarty_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.appknox.bakerstreet.Moriarty",
	HandlerType: (*MoriartyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Moriarty_Info_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _Moriarty_Echo_Handler,
		},
		{
			MethodName: "LaunchApp",
			Handler:    _Moriarty_LaunchApp_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Moriarty_HealthCheck_Handler,
		},
		{
			MethodName: "RemovePackage",
			Handler:    _Moriarty_RemovePackage_Handler,
		},
		{
			MethodName: "InstallPackage",
			Handler:    _Moriarty_InstallPackage_Handler,
		},
		{
			MethodName: "ListPackages",
			Handler:    _Moriarty_ListPackages_Handler,
		},
		{
			MethodName: "ConfigureProxy",
			Handler:    _Moriarty_ConfigureProxy_Handler,
		},
		{
			MethodName: "ConfigureGadget",
			Handler:    _Moriarty_ConfigureGadget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bakerstreet.proto",
}

// Client API for Mycroft service

type MycroftClient interface {
	Poll(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Message, error)
	PushFinding(ctx context.Context, in *Finding, opts ...grpc.CallOption) (*Message, error)
}

type mycroftClient struct {
	cc *grpc.ClientConn
}

func NewMycroftClient(cc *grpc.ClientConn) MycroftClient {
	return &mycroftClient{cc}
}

func (c *mycroftClient) Poll(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Mycroft/Poll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mycroftClient) PushFinding(ctx context.Context, in *Finding, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := grpc.Invoke(ctx, "/com.appknox.bakerstreet.Mycroft/PushFinding", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mycroft service

type MycroftServer interface {
	Poll(context.Context, *Device) (*Message, error)
	PushFinding(context.Context, *Finding) (*Message, error)
}

func RegisterMycroftServer(s *grpc.Server, srv MycroftServer) {
	s.RegisterService(&_Mycroft_serviceDesc, srv)
}

func _Mycroft_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MycroftServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Mycroft/Poll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MycroftServer).Poll(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mycroft_PushFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Finding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MycroftServer).PushFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.appknox.bakerstreet.Mycroft/PushFinding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MycroftServer).PushFinding(ctx, req.(*Finding))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mycroft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.appknox.bakerstreet.Mycroft",
	HandlerType: (*MycroftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Poll",
			Handler:    _Mycroft_Poll_Handler,
		},
		{
			MethodName: "PushFinding",
			Handler:    _Mycroft_PushFinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bakerstreet.proto",
}

func init() { proto.RegisterFile("bakerstreet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0xc7, 0xe5, 0xc4, 0x04, 0x67, 0x68, 0x83, 0xba, 0xaa, 0x54, 0x94, 0x4b, 0x5d, 0x4e, 0x39,
	0xf9, 0x90, 0x3e, 0x41, 0x14, 0xfa, 0x41, 0x15, 0x5a, 0x97, 0x40, 0xef, 0x83, 0x3d, 0xd8, 0x2b,
	0xcc, 0xee, 0x6a, 0x77, 0x1c, 0x85, 0x4b, 0x5f, 0xa7, 0xef, 0xd7, 0x27, 0xa8, 0x6c, 0x19, 0xd2,
	0xaa, 0x22, 0x70, 0xf0, 0x71, 0x3e, 0xfc, 0xfb, 0xcf, 0x8c, 0xfe, 0x5e, 0x78, 0xb5, 0xc0, 0x15,
	0x59, 0xc7, 0x96, 0x88, 0x23, 0x63, 0x35, 0x6b, 0xf1, 0x26, 0xd1, 0xeb, 0x08, 0x8d, 0x59, 0x29,
	0xfd, 0x18, 0xfd, 0x55, 0x1e, 0xce, 0xa1, 0x3b, 0x21, 0xe7, 0x30, 0x23, 0x21, 0xc0, 0x1f, 0x21,
	0xe3, 0xc0, 0x0b, 0xbd, 0xab, 0xf3, 0xa9, 0x9f, 0x22, 0xa3, 0x78, 0x0d, 0x9d, 0x99, 0xe4, 0x82,
	0x06, 0x27, 0x75, 0xb2, 0xc3, 0x55, 0x20, 0x42, 0xe8, 0x8d, 0xc8, 0x25, 0x56, 0x1a, 0x96, 0x5a,
	0x0d, 0x4e, 0xeb, 0x5a, 0x2f, 0x7d, 0x4a, 0x0d, 0x43, 0x08, 0x62, 0x4c, 0x56, 0x98, 0x91, 0xab,
	0x18, 0x5f, 0x71, 0x4d, 0x6e, 0xe0, 0x85, 0xa7, 0x15, 0x43, 0x55, 0xc1, 0xf0, 0x27, 0x9c, 0x8d,
	0xe8, 0x41, 0x26, 0xb5, 0xee, 0xbc, 0x94, 0xe9, 0x56, 0xb7, 0x2c, 0x65, 0x2a, 0x2e, 0x21, 0x18,
	0xbb, 0x19, 0x2e, 0x0a, 0xe2, 0x5a, 0x3a, 0x98, 0x06, 0xb2, 0x89, 0xab, 0x5a, 0x5c, 0x20, 0x2f,
	0xb5, 0x5d, 0xd7, 0xd2, 0x9d, 0x69, 0x60, 0x9a, 0x58, 0x5c, 0x41, 0x7f, 0x5b, 0xfb, 0x41, 0xd6,
	0x55, 0xd3, 0xf9, 0x35, 0xb6, 0x6f, 0xfe, 0x4d, 0x0f, 0x6f, 0xa0, 0xfb, 0x51, 0xaa, 0x54, 0xaa,
	0xec, 0x69, 0x49, 0xef, 0x99, 0x25, 0x4f, 0xfe, 0x5b, 0xf2, 0xfa, 0x77, 0x07, 0x82, 0x89, 0xb6,
	0x12, 0x2d, 0x6f, 0xc4, 0x18, 0xfc, 0xb1, 0x5a, 0x6a, 0x11, 0x46, 0x7b, 0x4e, 0x1d, 0x35, 0x77,
	0xbe, 0x7c, 0xbb, 0xb7, 0xa3, 0x39, 0xc8, 0x17, 0xf0, 0x3f, 0x24, 0xf9, 0x31, 0xa8, 0x83, 0x1d,
	0xe2, 0x1b, 0x9c, 0xdf, 0x61, 0xa9, 0x92, 0xfc, 0xc6, 0x98, 0x56, 0x80, 0xdf, 0xa1, 0xf7, 0x99,
	0xb0, 0xe0, 0xfc, 0x36, 0xa7, 0x64, 0xd5, 0x0a, 0xf2, 0x1e, 0x5e, 0x4e, 0x69, 0xad, 0x1f, 0xa8,
	0xb1, 0x4c, 0x2b, 0xd0, 0x19, 0x5c, 0x8c, 0x95, 0x63, 0x2c, 0x8a, 0x36, 0xa9, 0xf7, 0xf0, 0xe2,
	0x4e, 0x3a, 0xde, 0x79, 0xfb, 0x30, 0xf3, 0xdd, 0xde, 0x8e, 0x1d, 0x64, 0x06, 0x17, 0xb7, 0x5a,
	0x2d, 0x65, 0x56, 0x5a, 0x8a, 0xad, 0x7e, 0xdc, 0xb4, 0x32, 0xea, 0x1c, 0xfa, 0x3b, 0xea, 0x27,
	0x4c, 0x33, 0xe2, 0x36, 0xb0, 0xd7, 0xbf, 0x3c, 0xe8, 0x4e, 0x36, 0x89, 0xd5, 0x4b, 0xae, 0x3c,
	0x1f, 0xeb, 0xa2, 0x10, 0x87, 0x1c, 0x7d, 0x9c, 0xad, 0xe2, 0xd2, 0xe5, 0xdb, 0x5f, 0x72, 0xff,
	0x07, 0x4d, 0xc7, 0x61, 0xe4, 0xe2, 0xac, 0x7e, 0xfa, 0xde, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x21, 0x6e, 0xe0, 0x1c, 0x0f, 0x05, 0x00, 0x00,
}
