// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: bakerstreet/bakerstreet_bridge.proto

package bakerstreet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_UNKNOWN          CommandType = 0
	CommandType_COMMAND_ECHO             CommandType = 1
	CommandType_COMMAND_LAUNCH_APP       CommandType = 2
	CommandType_COMMAND_CLEAR_PROXY      CommandType = 3
	CommandType_COMMAND_HEALTH_CHECK     CommandType = 4
	CommandType_COMMAND_REMOVE_PACKAGE   CommandType = 5
	CommandType_COMMAND_INSTALL_PACKAGE  CommandType = 6
	CommandType_COMMAND_CONFIGURE_PROXY  CommandType = 7
	CommandType_COMMAND_CONFIGURE_GADGET CommandType = 8
	CommandType_COMMAND_START_AUTO_PILOT CommandType = 9
	CommandType_COMMAND_CLEAN            CommandType = 10
	CommandType_COMMAND_INFO             CommandType = 11
	CommandType_COMMAND_INFO_V2          CommandType = 12
	CommandType_COMMAND_LIST_PACKAGES    CommandType = 13
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "COMMAND_UNKNOWN",
		1:  "COMMAND_ECHO",
		2:  "COMMAND_LAUNCH_APP",
		3:  "COMMAND_CLEAR_PROXY",
		4:  "COMMAND_HEALTH_CHECK",
		5:  "COMMAND_REMOVE_PACKAGE",
		6:  "COMMAND_INSTALL_PACKAGE",
		7:  "COMMAND_CONFIGURE_PROXY",
		8:  "COMMAND_CONFIGURE_GADGET",
		9:  "COMMAND_START_AUTO_PILOT",
		10: "COMMAND_CLEAN",
		11: "COMMAND_INFO",
		12: "COMMAND_INFO_V2",
		13: "COMMAND_LIST_PACKAGES",
	}
	CommandType_value = map[string]int32{
		"COMMAND_UNKNOWN":          0,
		"COMMAND_ECHO":             1,
		"COMMAND_LAUNCH_APP":       2,
		"COMMAND_CLEAR_PROXY":      3,
		"COMMAND_HEALTH_CHECK":     4,
		"COMMAND_REMOVE_PACKAGE":   5,
		"COMMAND_INSTALL_PACKAGE":  6,
		"COMMAND_CONFIGURE_PROXY":  7,
		"COMMAND_CONFIGURE_GADGET": 8,
		"COMMAND_START_AUTO_PILOT": 9,
		"COMMAND_CLEAN":            10,
		"COMMAND_INFO":             11,
		"COMMAND_INFO_V2":          12,
		"COMMAND_LIST_PACKAGES":    13,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_bakerstreet_bakerstreet_bridge_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_bakerstreet_bakerstreet_bridge_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{0}
}

// Sent from cloud relay → device through the bidi stream.
type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                // UUID for request/response correlation
	Type      CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=com.appknox.bakerstreet.CommandType" json:"type,omitempty"` // Which RPC to invoke
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_Echo
	//	*Command_LaunchApp
	//	*Command_ClearProxy
	//	*Command_HealthCheck
	//	*Command_RemovePackage
	//	*Command_InstallPackage
	//	*Command_ConfigureProxy
	//	*Command_ConfigureGadget
	//	*Command_StartAutoPilot
	//	*Command_Clean
	//	*Command_Info
	//	*Command_InfoV2
	//	*Command_ListPackages
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_UNKNOWN
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetEcho() *Message {
	if x != nil {
		if x, ok := x.Payload.(*Command_Echo); ok {
			return x.Echo
		}
	}
	return nil
}

func (x *Command) GetLaunchApp() *App {
	if x != nil {
		if x, ok := x.Payload.(*Command_LaunchApp); ok {
			return x.LaunchApp
		}
	}
	return nil
}

func (x *Command) GetClearProxy() *Empty {
	if x != nil {
		if x, ok := x.Payload.(*Command_ClearProxy); ok {
			return x.ClearProxy
		}
	}
	return nil
}

func (x *Command) GetHealthCheck() *Empty {
	if x != nil {
		if x, ok := x.Payload.(*Command_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

func (x *Command) GetRemovePackage() *App {
	if x != nil {
		if x, ok := x.Payload.(*Command_RemovePackage); ok {
			return x.RemovePackage
		}
	}
	return nil
}

func (x *Command) GetInstallPackage() *InstallReq {
	if x != nil {
		if x, ok := x.Payload.(*Command_InstallPackage); ok {
			return x.InstallPackage
		}
	}
	return nil
}

func (x *Command) GetConfigureProxy() *ConfigProxyReq {
	if x != nil {
		if x, ok := x.Payload.(*Command_ConfigureProxy); ok {
			return x.ConfigureProxy
		}
	}
	return nil
}

func (x *Command) GetConfigureGadget() *App {
	if x != nil {
		if x, ok := x.Payload.(*Command_ConfigureGadget); ok {
			return x.ConfigureGadget
		}
	}
	return nil
}

func (x *Command) GetStartAutoPilot() *AutoPilotConfig {
	if x != nil {
		if x, ok := x.Payload.(*Command_StartAutoPilot); ok {
			return x.StartAutoPilot
		}
	}
	return nil
}

func (x *Command) GetClean() *CleanOptions {
	if x != nil {
		if x, ok := x.Payload.(*Command_Clean); ok {
			return x.Clean
		}
	}
	return nil
}

func (x *Command) GetInfo() *Empty {
	if x != nil {
		if x, ok := x.Payload.(*Command_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *Command) GetInfoV2() *Empty {
	if x != nil {
		if x, ok := x.Payload.(*Command_InfoV2); ok {
			return x.InfoV2
		}
	}
	return nil
}

func (x *Command) GetListPackages() *Empty {
	if x != nil {
		if x, ok := x.Payload.(*Command_ListPackages); ok {
			return x.ListPackages
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_Echo struct {
	Echo *Message `protobuf:"bytes,10,opt,name=echo,proto3,oneof"`
}

type Command_LaunchApp struct {
	LaunchApp *App `protobuf:"bytes,11,opt,name=launch_app,json=launchApp,proto3,oneof"`
}

type Command_ClearProxy struct {
	ClearProxy *Empty `protobuf:"bytes,12,opt,name=clear_proxy,json=clearProxy,proto3,oneof"`
}

type Command_HealthCheck struct {
	HealthCheck *Empty `protobuf:"bytes,13,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

type Command_RemovePackage struct {
	RemovePackage *App `protobuf:"bytes,14,opt,name=remove_package,json=removePackage,proto3,oneof"`
}

type Command_InstallPackage struct {
	InstallPackage *InstallReq `protobuf:"bytes,15,opt,name=install_package,json=installPackage,proto3,oneof"`
}

type Command_ConfigureProxy struct {
	ConfigureProxy *ConfigProxyReq `protobuf:"bytes,16,opt,name=configure_proxy,json=configureProxy,proto3,oneof"`
}

type Command_ConfigureGadget struct {
	ConfigureGadget *App `protobuf:"bytes,17,opt,name=configure_gadget,json=configureGadget,proto3,oneof"`
}

type Command_StartAutoPilot struct {
	StartAutoPilot *AutoPilotConfig `protobuf:"bytes,18,opt,name=start_auto_pilot,json=startAutoPilot,proto3,oneof"`
}

type Command_Clean struct {
	Clean *CleanOptions `protobuf:"bytes,19,opt,name=clean,proto3,oneof"`
}

type Command_Info struct {
	Info *Empty `protobuf:"bytes,20,opt,name=info,proto3,oneof"`
}

type Command_InfoV2 struct {
	InfoV2 *Empty `protobuf:"bytes,21,opt,name=info_v2,json=infoV2,proto3,oneof"`
}

type Command_ListPackages struct {
	ListPackages *Empty `protobuf:"bytes,22,opt,name=list_packages,json=listPackages,proto3,oneof"`
}

func (*Command_Echo) isCommand_Payload() {}

func (*Command_LaunchApp) isCommand_Payload() {}

func (*Command_ClearProxy) isCommand_Payload() {}

func (*Command_HealthCheck) isCommand_Payload() {}

func (*Command_RemovePackage) isCommand_Payload() {}

func (*Command_InstallPackage) isCommand_Payload() {}

func (*Command_ConfigureProxy) isCommand_Payload() {}

func (*Command_ConfigureGadget) isCommand_Payload() {}

func (*Command_StartAutoPilot) isCommand_Payload() {}

func (*Command_Clean) isCommand_Payload() {}

func (*Command_Info) isCommand_Payload() {}

func (*Command_InfoV2) isCommand_Payload() {}

func (*Command_ListPackages) isCommand_Payload() {}

// Sent from device → cloud relay through the bidi stream.
type CommandResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Must match the Command's request_id
	Success   bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // Error message if success=false
	// Types that are valid to be assigned to Result:
	//
	//	*CommandResponse_Message
	//	*CommandResponse_Device
	//	*CommandResponse_DeviceV2
	//	*CommandResponse_Apps
	Result        isCommandResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResponse) GetResult() isCommandResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Result.(*CommandResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *CommandResponse) GetDevice() *Device {
	if x != nil {
		if x, ok := x.Result.(*CommandResponse_Device); ok {
			return x.Device
		}
	}
	return nil
}

func (x *CommandResponse) GetDeviceV2() *DeviceV2 {
	if x != nil {
		if x, ok := x.Result.(*CommandResponse_DeviceV2); ok {
			return x.DeviceV2
		}
	}
	return nil
}

func (x *CommandResponse) GetApps() *Apps {
	if x != nil {
		if x, ok := x.Result.(*CommandResponse_Apps); ok {
			return x.Apps
		}
	}
	return nil
}

type isCommandResponse_Result interface {
	isCommandResponse_Result()
}

type CommandResponse_Message struct {
	Message *Message `protobuf:"bytes,10,opt,name=message,proto3,oneof"` // Echo, LaunchApp, ClearProxy, HealthCheck,
}

type CommandResponse_Device struct {
	// RemovePackage, InstallPackage, ConfigureProxy,
	// ConfigureGadget, StartAutoPilot, Clean
	Device *Device `protobuf:"bytes,11,opt,name=device,proto3,oneof"` // Info
}

type CommandResponse_DeviceV2 struct {
	DeviceV2 *DeviceV2 `protobuf:"bytes,12,opt,name=device_v2,json=deviceV2,proto3,oneof"` // InfoV2
}

type CommandResponse_Apps struct {
	Apps *Apps `protobuf:"bytes,13,opt,name=apps,proto3,oneof"` // ListPackages
}

func (*CommandResponse_Message) isCommandResponse_Result() {}

func (*CommandResponse_Device) isCommandResponse_Result() {}

func (*CommandResponse_DeviceV2) isCommandResponse_Result() {}

func (*CommandResponse_Apps) isCommandResponse_Result() {}

// First message a device sends after opening the stream.
type DeviceRegistration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                         // Unique device UUID
	CustomIdentifier string                 `protobuf:"bytes,2,opt,name=custom_identifier,json=customIdentifier,proto3" json:"custom_identifier,omitempty"` // Human-readable name / alias
	Platform         int32                  `protobuf:"varint,3,opt,name=platform,proto3" json:"platform,omitempty"`                                        // Platform enum (matches Device.Platform)
	AgentVersion     string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`             // Version of the device agent
	AuthToken        string                 `protobuf:"bytes,5,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`                      // Pre-shared secret or JWT
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeviceRegistration) Reset() {
	*x = DeviceRegistration{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRegistration) ProtoMessage() {}

func (x *DeviceRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRegistration.ProtoReflect.Descriptor instead.
func (*DeviceRegistration) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceRegistration) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceRegistration) GetCustomIdentifier() string {
	if x != nil {
		return x.CustomIdentifier
	}
	return ""
}

func (x *DeviceRegistration) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *DeviceRegistration) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *DeviceRegistration) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type RegistrationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Reason if rejected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegistrationAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Everything the device sends over the bidi stream.
type DeviceMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DeviceMessage_Registration
	//	*DeviceMessage_Response
	Payload       isDeviceMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMessage) Reset() {
	*x = DeviceMessage{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMessage) ProtoMessage() {}

func (x *DeviceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMessage.ProtoReflect.Descriptor instead.
func (*DeviceMessage) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceMessage) GetPayload() isDeviceMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeviceMessage) GetRegistration() *DeviceRegistration {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *DeviceMessage) GetResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.Payload.(*DeviceMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isDeviceMessage_Payload interface {
	isDeviceMessage_Payload()
}

type DeviceMessage_Registration struct {
	Registration *DeviceRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"` // First message after connecting
}

type DeviceMessage_Response struct {
	Response *CommandResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"` // All subsequent messages
}

func (*DeviceMessage_Registration) isDeviceMessage_Payload() {}

func (*DeviceMessage_Response) isDeviceMessage_Payload() {}

// Everything the cloud relay sends over the bidi stream.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Ack
	//	*ServerMessage_Command
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetAck() *RegistrationAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Ack struct {
	Ack *RegistrationAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"` // Reply to registration
}

type ServerMessage_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"` // Command to execute on device
}

func (*ServerMessage_Ack) isServerMessage_Payload() {}

func (*ServerMessage_Command) isServerMessage_Payload() {}

type TargetedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Data          *Message               `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetedMessage) Reset() {
	*x = TargetedMessage{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetedMessage) ProtoMessage() {}

func (x *TargetedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetedMessage.ProtoReflect.Descriptor instead.
func (*TargetedMessage) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *TargetedMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TargetedMessage) GetData() *Message {
	if x != nil {
		return x.Data
	}
	return nil
}

type TargetedApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Data          *App                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetedApp) Reset() {
	*x = TargetedApp{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetedApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetedApp) ProtoMessage() {}

func (x *TargetedApp) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetedApp.ProtoReflect.Descriptor instead.
func (*TargetedApp) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *TargetedApp) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TargetedApp) GetData() *App {
	if x != nil {
		return x.Data
	}
	return nil
}

type TargetedEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetedEmpty) Reset() {
	*x = TargetedEmpty{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetedEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetedEmpty) ProtoMessage() {}

func (x *TargetedEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetedEmpty.ProtoReflect.Descriptor instead.
func (*TargetedEmpty) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *TargetedEmpty) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type TargetedInstallReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Data          *InstallReq            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetedInstallReq) Reset() {
	*x = TargetedInstallReq{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetedInstallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetedInstallReq) ProtoMessage() {}

func (x *TargetedInstallReq) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetedInstallReq.ProtoReflect.Descriptor instead.
func (*TargetedInstallReq) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *TargetedInstallReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TargetedInstallReq) GetData() *InstallReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type TargetedConfigProxyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Data          *ConfigProxyReq        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetedConfigProxyReq) Reset() {
	*x = TargetedConfigProxyReq{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetedConfigProxyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetedConfigProxyReq) ProtoMessage() {}

func (x *TargetedConfigProxyReq) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetedConfigProxyReq.ProtoReflect.Descriptor instead.
func (*TargetedConfigProxyReq) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *TargetedConfigProxyReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TargetedConfigProxyReq) GetData() *ConfigProxyReq {
	if x != nil {
		return x.Data
	}
	return nil
}

type TargetedAutoPilotConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Data          *AutoPilotConfig       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetedAutoPilotConfig) Reset() {
	*x = TargetedAutoPilotConfig{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetedAutoPilotConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetedAutoPilotConfig) ProtoMessage() {}

func (x *TargetedAutoPilotConfig) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetedAutoPilotConfig.ProtoReflect.Descriptor instead.
func (*TargetedAutoPilotConfig) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *TargetedAutoPilotConfig) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TargetedAutoPilotConfig) GetData() *AutoPilotConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

type TargetedCleanOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Data          *CleanOptions          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetedCleanOptions) Reset() {
	*x = TargetedCleanOptions{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetedCleanOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetedCleanOptions) ProtoMessage() {}

func (x *TargetedCleanOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetedCleanOptions.ProtoReflect.Descriptor instead.
func (*TargetedCleanOptions) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *TargetedCleanOptions) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TargetedCleanOptions) GetData() *CleanOptions {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*ConnectedDevice     `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *DeviceList) GetDevices() []*ConnectedDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ConnectedDevice struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CustomIdentifier string                 `protobuf:"bytes,2,opt,name=custom_identifier,json=customIdentifier,proto3" json:"custom_identifier,omitempty"`
	Platform         int32                  `protobuf:"varint,3,opt,name=platform,proto3" json:"platform,omitempty"`
	AgentVersion     string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ConnectedAt      int64                  `protobuf:"varint,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"` // Unix timestamp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectedDevice) Reset() {
	*x = ConnectedDevice{}
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedDevice) ProtoMessage() {}

func (x *ConnectedDevice) ProtoReflect() protoreflect.Message {
	mi := &file_bakerstreet_bakerstreet_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedDevice.ProtoReflect.Descriptor instead.
func (*ConnectedDevice) Descriptor() ([]byte, []int) {
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *ConnectedDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConnectedDevice) GetCustomIdentifier() string {
	if x != nil {
		return x.CustomIdentifier
	}
	return ""
}

func (x *ConnectedDevice) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *ConnectedDevice) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *ConnectedDevice) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

var File_bakerstreet_bakerstreet_bridge_proto protoreflect.FileDescriptor

const file_bakerstreet_bakerstreet_bridge_proto_rawDesc = "" +
	"\n" +
	"$bakerstreet/bakerstreet_bridge.proto\x12\x17com.appknox.bakerstreet\x1a\x1dbakerstreet/bakerstreet.proto\"\xef\a\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.com.appknox.bakerstreet.CommandTypeR\x04type\x126\n" +
	"\x04echo\x18\n" +
	" \x01(\v2 .com.appknox.bakerstreet.MessageH\x00R\x04echo\x12=\n" +
	"\n" +
	"launch_app\x18\v \x01(\v2\x1c.com.appknox.bakerstreet.AppH\x00R\tlaunchApp\x12A\n" +
	"\vclear_proxy\x18\f \x01(\v2\x1e.com.appknox.bakerstreet.EmptyH\x00R\n" +
	"clearProxy\x12C\n" +
	"\fhealth_check\x18\r \x01(\v2\x1e.com.appknox.bakerstreet.EmptyH\x00R\vhealthCheck\x12E\n" +
	"\x0eremove_package\x18\x0e \x01(\v2\x1c.com.appknox.bakerstreet.AppH\x00R\rremovePackage\x12N\n" +
	"\x0finstall_package\x18\x0f \x01(\v2#.com.appknox.bakerstreet.InstallReqH\x00R\x0einstallPackage\x12R\n" +
	"\x0fconfigure_proxy\x18\x10 \x01(\v2'.com.appknox.bakerstreet.ConfigProxyReqH\x00R\x0econfigureProxy\x12I\n" +
	"\x10configure_gadget\x18\x11 \x01(\v2\x1c.com.appknox.bakerstreet.AppH\x00R\x0fconfigureGadget\x12T\n" +
	"\x10start_auto_pilot\x18\x12 \x01(\v2(.com.appknox.bakerstreet.AutoPilotConfigH\x00R\x0estartAutoPilot\x12=\n" +
	"\x05clean\x18\x13 \x01(\v2%.com.appknox.bakerstreet.CleanOptionsH\x00R\x05clean\x124\n" +
	"\x04info\x18\x14 \x01(\v2\x1e.com.appknox.bakerstreet.EmptyH\x00R\x04info\x129\n" +
	"\ainfo_v2\x18\x15 \x01(\v2\x1e.com.appknox.bakerstreet.EmptyH\x00R\x06infoV2\x12E\n" +
	"\rlist_packages\x18\x16 \x01(\v2\x1e.com.appknox.bakerstreet.EmptyH\x00R\flistPackagesB\t\n" +
	"\apayload\"\xda\x02\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12<\n" +
	"\amessage\x18\n" +
	" \x01(\v2 .com.appknox.bakerstreet.MessageH\x00R\amessage\x129\n" +
	"\x06device\x18\v \x01(\v2\x1f.com.appknox.bakerstreet.DeviceH\x00R\x06device\x12@\n" +
	"\tdevice_v2\x18\f \x01(\v2!.com.appknox.bakerstreet.DeviceV2H\x00R\bdeviceV2\x123\n" +
	"\x04apps\x18\r \x01(\v2\x1d.com.appknox.bakerstreet.AppsH\x00R\x04appsB\b\n" +
	"\x06result\"\xbe\x01\n" +
	"\x12DeviceRegistration\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12+\n" +
	"\x11custom_identifier\x18\x02 \x01(\tR\x10customIdentifier\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\x05R\bplatform\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x05 \x01(\tR\tauthToken\"G\n" +
	"\x0fRegistrationAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb5\x01\n" +
	"\rDeviceMessage\x12Q\n" +
	"\fregistration\x18\x01 \x01(\v2+.com.appknox.bakerstreet.DeviceRegistrationH\x00R\fregistration\x12F\n" +
	"\bresponse\x18\x02 \x01(\v2(.com.appknox.bakerstreet.CommandResponseH\x00R\bresponseB\t\n" +
	"\apayload\"\x96\x01\n" +
	"\rServerMessage\x12<\n" +
	"\x03ack\x18\x01 \x01(\v2(.com.appknox.bakerstreet.RegistrationAckH\x00R\x03ack\x12<\n" +
	"\acommand\x18\x02 \x01(\v2 .com.appknox.bakerstreet.CommandH\x00R\acommandB\t\n" +
	"\apayload\"d\n" +
	"\x0fTargetedMessage\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x124\n" +
	"\x04data\x18\x02 \x01(\v2 .com.appknox.bakerstreet.MessageR\x04data\"\\\n" +
	"\vTargetedApp\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x120\n" +
	"\x04data\x18\x02 \x01(\v2\x1c.com.appknox.bakerstreet.AppR\x04data\",\n" +
	"\rTargetedEmpty\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"j\n" +
	"\x12TargetedInstallReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x127\n" +
	"\x04data\x18\x02 \x01(\v2#.com.appknox.bakerstreet.InstallReqR\x04data\"r\n" +
	"\x16TargetedConfigProxyReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12;\n" +
	"\x04data\x18\x02 \x01(\v2'.com.appknox.bakerstreet.ConfigProxyReqR\x04data\"t\n" +
	"\x17TargetedAutoPilotConfig\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12<\n" +
	"\x04data\x18\x02 \x01(\v2(.com.appknox.bakerstreet.AutoPilotConfigR\x04data\"n\n" +
	"\x14TargetedCleanOptions\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x129\n" +
	"\x04data\x18\x02 \x01(\v2%.com.appknox.bakerstreet.CleanOptionsR\x04data\"P\n" +
	"\n" +
	"DeviceList\x12B\n" +
	"\adevices\x18\x01 \x03(\v2(.com.appknox.bakerstreet.ConnectedDeviceR\adevices\"\xbf\x01\n" +
	"\x0fConnectedDevice\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12+\n" +
	"\x11custom_identifier\x18\x02 \x01(\tR\x10customIdentifier\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\x05R\bplatform\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12!\n" +
	"\fconnected_at\x18\x05 \x01(\x03R\vconnectedAt*\xe6\x02\n" +
	"\vCommandType\x12\x13\n" +
	"\x0fCOMMAND_UNKNOWN\x10\x00\x12\x10\n" +
	"\fCOMMAND_ECHO\x10\x01\x12\x16\n" +
	"\x12COMMAND_LAUNCH_APP\x10\x02\x12\x17\n" +
	"\x13COMMAND_CLEAR_PROXY\x10\x03\x12\x18\n" +
	"\x14COMMAND_HEALTH_CHECK\x10\x04\x12\x1a\n" +
	"\x16COMMAND_REMOVE_PACKAGE\x10\x05\x12\x1b\n" +
	"\x17COMMAND_INSTALL_PACKAGE\x10\x06\x12\x1b\n" +
	"\x17COMMAND_CONFIGURE_PROXY\x10\a\x12\x1c\n" +
	"\x18COMMAND_CONFIGURE_GADGET\x10\b\x12\x1c\n" +
	"\x18COMMAND_START_AUTO_PILOT\x10\t\x12\x11\n" +
	"\rCOMMAND_CLEAN\x10\n" +
	"\x12\x10\n" +
	"\fCOMMAND_INFO\x10\v\x12\x13\n" +
	"\x0fCOMMAND_INFO_V2\x10\f\x12\x19\n" +
	"\x15COMMAND_LIST_PACKAGES\x10\r2o\n" +
	"\x0eMoriartyBridge\x12]\n" +
	"\aConnect\x12&.com.appknox.bakerstreet.DeviceMessage\x1a&.com.appknox.bakerstreet.ServerMessage(\x010\x012\xf7\t\n" +
	"\x10MoriartyDispatch\x12R\n" +
	"\x04Echo\x12(.com.appknox.bakerstreet.TargetedMessage\x1a .com.appknox.bakerstreet.Message\x12S\n" +
	"\tLaunchApp\x12$.com.appknox.bakerstreet.TargetedApp\x1a .com.appknox.bakerstreet.Message\x12V\n" +
	"\n" +
	"ClearProxy\x12&.com.appknox.bakerstreet.TargetedEmpty\x1a .com.appknox.bakerstreet.Message\x12W\n" +
	"\vHealthCheck\x12&.com.appknox.bakerstreet.TargetedEmpty\x1a .com.appknox.bakerstreet.Message\x12W\n" +
	"\rRemovePackage\x12$.com.appknox.bakerstreet.TargetedApp\x1a .com.appknox.bakerstreet.Message\x12_\n" +
	"\x0eInstallPackage\x12+.com.appknox.bakerstreet.TargetedInstallReq\x1a .com.appknox.bakerstreet.Message\x12c\n" +
	"\x0eConfigureProxy\x12/.com.appknox.bakerstreet.TargetedConfigProxyReq\x1a .com.appknox.bakerstreet.Message\x12Y\n" +
	"\x0fConfigureGadget\x12$.com.appknox.bakerstreet.TargetedApp\x1a .com.appknox.bakerstreet.Message\x12d\n" +
	"\x0eStartAutoPilot\x120.com.appknox.bakerstreet.TargetedAutoPilotConfig\x1a .com.appknox.bakerstreet.Message\x12X\n" +
	"\x05Clean\x12-.com.appknox.bakerstreet.TargetedCleanOptions\x1a .com.appknox.bakerstreet.Message\x12O\n" +
	"\x04Info\x12&.com.appknox.bakerstreet.TargetedEmpty\x1a\x1f.com.appknox.bakerstreet.Device\x12S\n" +
	"\x06InfoV2\x12&.com.appknox.bakerstreet.TargetedEmpty\x1a!.com.appknox.bakerstreet.DeviceV2\x12U\n" +
	"\fListPackages\x12&.com.appknox.bakerstreet.TargetedEmpty\x1a\x1d.com.appknox.bakerstreet.Apps\x12R\n" +
	"\vListDevices\x12\x1e.com.appknox.bakerstreet.Empty\x1a#.com.appknox.bakerstreet.DeviceListB Z\x1egithub.com/appknox/bakerstreetb\x06proto3"

var (
	file_bakerstreet_bakerstreet_bridge_proto_rawDescOnce sync.Once
	file_bakerstreet_bakerstreet_bridge_proto_rawDescData []byte
)

func file_bakerstreet_bakerstreet_bridge_proto_rawDescGZIP() []byte {
	file_bakerstreet_bakerstreet_bridge_proto_rawDescOnce.Do(func() {
		file_bakerstreet_bakerstreet_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bakerstreet_bakerstreet_bridge_proto_rawDesc), len(file_bakerstreet_bakerstreet_bridge_proto_rawDesc)))
	})
	return file_bakerstreet_bakerstreet_bridge_proto_rawDescData
}

var file_bakerstreet_bakerstreet_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bakerstreet_bakerstreet_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_bakerstreet_bakerstreet_bridge_proto_goTypes = []any{
	(CommandType)(0),                // 0: com.appknox.bakerstreet.CommandType
	(*Command)(nil),                 // 1: com.appknox.bakerstreet.Command
	(*CommandResponse)(nil),         // 2: com.appknox.bakerstreet.CommandResponse
	(*DeviceRegistration)(nil),      // 3: com.appknox.bakerstreet.DeviceRegistration
	(*RegistrationAck)(nil),         // 4: com.appknox.bakerstreet.RegistrationAck
	(*DeviceMessage)(nil),           // 5: com.appknox.bakerstreet.DeviceMessage
	(*ServerMessage)(nil),           // 6: com.appknox.bakerstreet.ServerMessage
	(*TargetedMessage)(nil),         // 7: com.appknox.bakerstreet.TargetedMessage
	(*TargetedApp)(nil),             // 8: com.appknox.bakerstreet.TargetedApp
	(*TargetedEmpty)(nil),           // 9: com.appknox.bakerstreet.TargetedEmpty
	(*TargetedInstallReq)(nil),      // 10: com.appknox.bakerstreet.TargetedInstallReq
	(*TargetedConfigProxyReq)(nil),  // 11: com.appknox.bakerstreet.TargetedConfigProxyReq
	(*TargetedAutoPilotConfig)(nil), // 12: com.appknox.bakerstreet.TargetedAutoPilotConfig
	(*TargetedCleanOptions)(nil),    // 13: com.appknox.bakerstreet.TargetedCleanOptions
	(*DeviceList)(nil),              // 14: com.appknox.bakerstreet.DeviceList
	(*ConnectedDevice)(nil),         // 15: com.appknox.bakerstreet.ConnectedDevice
	(*Message)(nil),                 // 16: com.appknox.bakerstreet.Message
	(*App)(nil),                     // 17: com.appknox.bakerstreet.App
	(*Empty)(nil),                   // 18: com.appknox.bakerstreet.Empty
	(*InstallReq)(nil),              // 19: com.appknox.bakerstreet.InstallReq
	(*ConfigProxyReq)(nil),          // 20: com.appknox.bakerstreet.ConfigProxyReq
	(*AutoPilotConfig)(nil),         // 21: com.appknox.bakerstreet.AutoPilotConfig
	(*CleanOptions)(nil),            // 22: com.appknox.bakerstreet.CleanOptions
	(*Device)(nil),                  // 23: com.appknox.bakerstreet.Device
	(*DeviceV2)(nil),                // 24: com.appknox.bakerstreet.DeviceV2
	(*Apps)(nil),                    // 25: com.appknox.bakerstreet.Apps
}
var file_bakerstreet_bakerstreet_bridge_proto_depIdxs = []int32{
	0,  // 0: com.appknox.bakerstreet.Command.type:type_name -> com.appknox.bakerstreet.CommandType
	16, // 1: com.appknox.bakerstreet.Command.echo:type_name -> com.appknox.bakerstreet.Message
	17, // 2: com.appknox.bakerstreet.Command.launch_app:type_name -> com.appknox.bakerstreet.App
	18, // 3: com.appknox.bakerstreet.Command.clear_proxy:type_name -> com.appknox.bakerstreet.Empty
	18, // 4: com.appknox.bakerstreet.Command.health_check:type_name -> com.appknox.bakerstreet.Empty
	17, // 5: com.appknox.bakerstreet.Command.remove_package:type_name -> com.appknox.bakerstreet.App
	19, // 6: com.appknox.bakerstreet.Command.install_package:type_name -> com.appknox.bakerstreet.InstallReq
	20, // 7: com.appknox.bakerstreet.Command.configure_proxy:type_name -> com.appknox.bakerstreet.ConfigProxyReq
	17, // 8: com.appknox.bakerstreet.Command.configure_gadget:type_name -> com.appknox.bakerstreet.App
	21, // 9: com.appknox.bakerstreet.Command.start_auto_pilot:type_name -> com.appknox.bakerstreet.AutoPilotConfig
	22, // 10: com.appknox.bakerstreet.Command.clean:type_name -> com.appknox.bakerstreet.CleanOptions
	18, // 11: com.appknox.bakerstreet.Command.info:type_name -> com.appknox.bakerstreet.Empty
	18, // 12: com.appknox.bakerstreet.Command.info_v2:type_name -> com.appknox.bakerstreet.Empty
	18, // 13: com.appknox.bakerstreet.Command.list_packages:type_name -> com.appknox.bakerstreet.Empty
	16, // 14: com.appknox.bakerstreet.CommandResponse.message:type_name -> com.appknox.bakerstreet.Message
	23, // 15: com.appknox.bakerstreet.CommandResponse.device:type_name -> com.appknox.bakerstreet.Device
	24, // 16: com.appknox.bakerstreet.CommandResponse.device_v2:type_name -> com.appknox.bakerstreet.DeviceV2
	25, // 17: com.appknox.bakerstreet.CommandResponse.apps:type_name -> com.appknox.bakerstreet.Apps
	3,  // 18: com.appknox.bakerstreet.DeviceMessage.registration:type_name -> com.appknox.bakerstreet.DeviceRegistration
	2,  // 19: com.appknox.bakerstreet.DeviceMessage.response:type_name -> com.appknox.bakerstreet.CommandResponse
	4,  // 20: com.appknox.bakerstreet.ServerMessage.ack:type_name -> com.appknox.bakerstreet.RegistrationAck
	1,  // 21: com.appknox.bakerstreet.ServerMessage.command:type_name -> com.appknox.bakerstreet.Command
	16, // 22: com.appknox.bakerstreet.TargetedMessage.data:type_name -> com.appknox.bakerstreet.Message
	17, // 23: com.appknox.bakerstreet.TargetedApp.data:type_name -> com.appknox.bakerstreet.App
	19, // 24: com.appknox.bakerstreet.TargetedInstallReq.data:type_name -> com.appknox.bakerstreet.InstallReq
	20, // 25: com.appknox.bakerstreet.TargetedConfigProxyReq.data:type_name -> com.appknox.bakerstreet.ConfigProxyReq
	21, // 26: com.appknox.bakerstreet.TargetedAutoPilotConfig.data:type_name -> com.appknox.bakerstreet.AutoPilotConfig
	22, // 27: com.appknox.bakerstreet.TargetedCleanOptions.data:type_name -> com.appknox.bakerstreet.CleanOptions
	15, // 28: com.appknox.bakerstreet.DeviceList.devices:type_name -> com.appknox.bakerstreet.ConnectedDevice
	5,  // 29: com.appknox.bakerstreet.MoriartyBridge.Connect:input_type -> com.appknox.bakerstreet.DeviceMessage
	7,  // 30: com.appknox.bakerstreet.MoriartyDispatch.Echo:input_type -> com.appknox.bakerstreet.TargetedMessage
	8,  // 31: com.appknox.bakerstreet.MoriartyDispatch.LaunchApp:input_type -> com.appknox.bakerstreet.TargetedApp
	9,  // 32: com.appknox.bakerstreet.MoriartyDispatch.ClearProxy:input_type -> com.appknox.bakerstreet.TargetedEmpty
	9,  // 33: com.appknox.bakerstreet.MoriartyDispatch.HealthCheck:input_type -> com.appknox.bakerstreet.TargetedEmpty
	8,  // 34: com.appknox.bakerstreet.MoriartyDispatch.RemovePackage:input_type -> com.appknox.bakerstreet.TargetedApp
	10, // 35: com.appknox.bakerstreet.MoriartyDispatch.InstallPackage:input_type -> com.appknox.bakerstreet.TargetedInstallReq
	11, // 36: com.appknox.bakerstreet.MoriartyDispatch.ConfigureProxy:input_type -> com.appknox.bakerstreet.TargetedConfigProxyReq
	8,  // 37: com.appknox.bakerstreet.MoriartyDispatch.ConfigureGadget:input_type -> com.appknox.bakerstreet.TargetedApp
	12, // 38: com.appknox.bakerstreet.MoriartyDispatch.StartAutoPilot:input_type -> com.appknox.bakerstreet.TargetedAutoPilotConfig
	13, // 39: com.appknox.bakerstreet.MoriartyDispatch.Clean:input_type -> com.appknox.bakerstreet.TargetedCleanOptions
	9,  // 40: com.appknox.bakerstreet.MoriartyDispatch.Info:input_type -> com.appknox.bakerstreet.TargetedEmpty
	9,  // 41: com.appknox.bakerstreet.MoriartyDispatch.InfoV2:input_type -> com.appknox.bakerstreet.TargetedEmpty
	9,  // 42: com.appknox.bakerstreet.MoriartyDispatch.ListPackages:input_type -> com.appknox.bakerstreet.TargetedEmpty
	18, // 43: com.appknox.bakerstreet.MoriartyDispatch.ListDevices:input_type -> com.appknox.bakerstreet.Empty
	6,  // 44: com.appknox.bakerstreet.MoriartyBridge.Connect:output_type -> com.appknox.bakerstreet.ServerMessage
	16, // 45: com.appknox.bakerstreet.MoriartyDispatch.Echo:output_type -> com.appknox.bakerstreet.Message
	16, // 46: com.appknox.bakerstreet.MoriartyDispatch.LaunchApp:output_type -> com.appknox.bakerstreet.Message
	16, // 47: com.appknox.bakerstreet.MoriartyDispatch.ClearProxy:output_type -> com.appknox.bakerstreet.Message
	16, // 48: com.appknox.bakerstreet.MoriartyDispatch.HealthCheck:output_type -> com.appknox.bakerstreet.Message
	16, // 49: com.appknox.bakerstreet.MoriartyDispatch.RemovePackage:output_type -> com.appknox.bakerstreet.Message
	16, // 50: com.appknox.bakerstreet.MoriartyDispatch.InstallPackage:output_type -> com.appknox.bakerstreet.Message
	16, // 51: com.appknox.bakerstreet.MoriartyDispatch.ConfigureProxy:output_type -> com.appknox.bakerstreet.Message
	16, // 52: com.appknox.bakerstreet.MoriartyDispatch.ConfigureGadget:output_type -> com.appknox.bakerstreet.Message
	16, // 53: com.appknox.bakerstreet.MoriartyDispatch.StartAutoPilot:output_type -> com.appknox.bakerstreet.Message
	16, // 54: com.appknox.bakerstreet.MoriartyDispatch.Clean:output_type -> com.appknox.bakerstreet.Message
	23, // 55: com.appknox.bakerstreet.MoriartyDispatch.Info:output_type -> com.appknox.bakerstreet.Device
	24, // 56: com.appknox.bakerstreet.MoriartyDispatch.InfoV2:output_type -> com.appknox.bakerstreet.DeviceV2
	25, // 57: com.appknox.bakerstreet.MoriartyDispatch.ListPackages:output_type -> com.appknox.bakerstreet.Apps
	14, // 58: com.appknox.bakerstreet.MoriartyDispatch.ListDevices:output_type -> com.appknox.bakerstreet.DeviceList
	44, // [44:59] is the sub-list for method output_type
	29, // [29:44] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_bakerstreet_bakerstreet_bridge_proto_init() }
func file_bakerstreet_bakerstreet_bridge_proto_init() {
	if File_bakerstreet_bakerstreet_bridge_proto != nil {
		return
	}
	file_bakerstreet_bakerstreet_proto_init()
	file_bakerstreet_bakerstreet_bridge_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_Echo)(nil),
		(*Command_LaunchApp)(nil),
		(*Command_ClearProxy)(nil),
		(*Command_HealthCheck)(nil),
		(*Command_RemovePackage)(nil),
		(*Command_InstallPackage)(nil),
		(*Command_ConfigureProxy)(nil),
		(*Command_ConfigureGadget)(nil),
		(*Command_StartAutoPilot)(nil),
		(*Command_Clean)(nil),
		(*Command_Info)(nil),
		(*Command_InfoV2)(nil),
		(*Command_ListPackages)(nil),
	}
	file_bakerstreet_bakerstreet_bridge_proto_msgTypes[1].OneofWrappers = []any{
		(*CommandResponse_Message)(nil),
		(*CommandResponse_Device)(nil),
		(*CommandResponse_DeviceV2)(nil),
		(*CommandResponse_Apps)(nil),
	}
	file_bakerstreet_bakerstreet_bridge_proto_msgTypes[4].OneofWrappers = []any{
		(*DeviceMessage_Registration)(nil),
		(*DeviceMessage_Response)(nil),
	}
	file_bakerstreet_bakerstreet_bridge_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bakerstreet_bakerstreet_bridge_proto_rawDesc), len(file_bakerstreet_bakerstreet_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_bakerstreet_bakerstreet_bridge_proto_goTypes,
		DependencyIndexes: file_bakerstreet_bakerstreet_bridge_proto_depIdxs,
		EnumInfos:         file_bakerstreet_bakerstreet_bridge_proto_enumTypes,
		MessageInfos:      file_bakerstreet_bakerstreet_bridge_proto_msgTypes,
	}.Build()
	File_bakerstreet_bakerstreet_bridge_proto = out.File
	file_bakerstreet_bakerstreet_bridge_proto_goTypes = nil
	file_bakerstreet_bakerstreet_bridge_proto_depIdxs = nil
}
